columns:
  - id: int
  - Nitrogen: int
  - Phosphorus: int
  - Potassium: int
  - Temperature: float
  - Humidity: float
  - pH_Value: float
  - Rainfall: float
  - Crop: category
  - Crop_Encoded: int

numerical_columns:
  - Nitrogen
  - Phosphorus
  - Potassium
  - Temperature
  - Humidity
  - pH_Value
  - Rainfall
  - Crop_Encoded
categorical_columns: 
  - Crop

drop_columns: _id
# # for data transformation
num_features:
  - Nitrogen
  - Phosphorus
  - Potassium
  - Temperature
  - Humidity
  - pH_Value
  - Rainfall

# mm_columns:
#   - Annual_Premium